on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Deploy Kubernetes Manifests
        timeout-minutes: 10
        run: |     
          export KUBECONFIG=skaffold.yaml
          kubectl apply  -f release/kubernetes-manifests/
          