on: [push]
env:
  DEV_CLUSTER_KUBECONF: ${{ secrets.DEV_CLUSTER_KUBECONF }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Kubernetes Manifests
        timeout-minutes: 10
        run: |
          sudo mkdir -p /kubeconf
          echo "$DEV_CLUSTER_KUBECONF" > /kubeconf/kubeconf.conf        
          export KUBECONFIG=/kubeconf/kubeconf.conf 
          kubectl apply -f kubernetes-manifests/