on: [push]
jobs:
  code-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      env:
        DOTNET_INSTALL_DIR: "./.dotnet"
      with:
        dotnet-version: '8.0'
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Go Unit Tests
      timeout-minutes: 10
      run: |
        for SERVICE in "shippingservice" "productcatalogservice"; do
          echo "testing $SERVICE..."
          pushd src/$SERVICE
          go test
          popd
        done
    - name: C# Unit Tests
      timeout-minutes: 10
      run: |
        dotnet test src/cartservice/
  deployment-tests:
    runs-on: ubuntu-latest
    needs: code-tests
    strategy:
      matrix:
        profile: ["local-code"]
      fail-fast: true
    steps:
      - name: Placeholder Step
        run: echo "Running deployment tests..."
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Deploy Kubernetes Manifests
        timeout-minutes: 10
        run: |     
          export KUBECONFIG=skaffold.yaml
          kubectl apply  -f release/kubernetes-manifests.yaml
        
      - name: Wait For Pods
        timeout-minutes: 20
        run: |
          export KUBECONFIG=skaffold.yaml
          set -x
          kubectl wait --for=condition=available --timeout=1000s deployment/redis-cart
          kubectl wait --for=condition=available --timeout=1000s deployment/adservice
          kubectl wait --for=condition=available --timeout=1000s deployment/cartservice
          kubectl wait --for=condition=available --timeout=1000s deployment/checkoutservice
          kubectl wait --for=condition=available --timeout=1000s deployment/currencyservice
          kubectl wait --for=condition=available --timeout=1000s deployment/emailservice
          kubectl wait --for=condition=available --timeout=1000s deployment/frontend
          kubectl wait --for=condition=available --timeout=1000s deployment/loadgenerator
          kubectl wait --for=condition=available --timeout=1000s deployment/paymentservice
          kubectl wait --for=condition=available --timeout=1000s deployment/productcatalogservice
          kubectl wait --for=condition=available --timeout=1000s deployment/recommendationservice
          kubectl wait --for=condition=available --timeout=1000s deployment/shippingservice
      - name: Smoke Test
        timeout-minutes: 5
        run: |
          export KUBECONFIG=skaffold.yaml
          set -x
          # start fresh loadgenerator pod
          kubectl delete pod -l app=loadgenerator
          # wait for requests to come in
          REQUEST_COUNT="0"
          while [[ "$REQUEST_COUNT"  -lt "50"  ]]; do
              sleep 5
              REQUEST_COUNT=$(kubectl logs -l app=loadgenerator | grep Aggregated | awk '{print $2}')
          done
          # ensure there are no errors hitting endpoints
          ERROR_COUNT=$(kubectl logs -l app=loadgenerator | grep Aggregated | awk '{print $3}' | sed "s/[(][^)]*[)]//g")
          if [[ "$ERROR_COUNT" -gt "0" ]]; then
            exit 1
          fi          